// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxnXsECnLSJ06ejyVbK3WmsDSa6KjfEik',
    appId: '1:713609039480:web:e7d2e8c6bd99a5bc9c678d',
    messagingSenderId: '713609039480',
    projectId: 'aries-eadmin',
    authDomain: 'aries-eadmin.firebaseapp.com',
    storageBucket: 'aries-eadmin.appspot.com',
    measurementId: 'G-91CRQ5MTRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCar_rSW3YVw2Jb5wpwzXGwfp3q8iFlaFE',
    appId: '1:713609039480:android:4c0c9462b01b9c629c678d',
    messagingSenderId: '713609039480',
    projectId: 'aries-eadmin',
    storageBucket: 'aries-eadmin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWISrb_vqzp_OwrZo9TYRdE_woDYnYzbc',
    appId: '1:713609039480:ios:647652dd31c493289c678d',
    messagingSenderId: '713609039480',
    projectId: 'aries-eadmin',
    storageBucket: 'aries-eadmin.appspot.com',
    iosBundleId: 'com.example.edmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWISrb_vqzp_OwrZo9TYRdE_woDYnYzbc',
    appId: '1:713609039480:ios:f921b409b9c9c88d9c678d',
    messagingSenderId: '713609039480',
    projectId: 'aries-eadmin',
    storageBucket: 'aries-eadmin.appspot.com',
    iosBundleId: 'com.example.edmin.RunnerTests',
  );
}
